- op: add
  path: /spec/rules/-
  value:
    host: "*.app.github.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-debug-reaction-service
            port:
              number: 8080
